### ISSUE TITLE
Change Projects to Team in Home Page

### ISSUE THREAD

**Issue by aryav-022** [GDSC-NSUT/website#5]
## You have to change the text and redirect path.

![image](https://github.com/GDSC-NSUT/website/assets/69618788/f2d394bd-b06b-447a-82f9-a98507983571)

**Comment by ManasMadan** [comment]
@aryav-022 Please assign this issue to me. I hope the image and description will be same even after changing the Projects Text to Team Text and redirect path to team page

**Comment by aryav-022** [comment]
@ManasMadan assigned this issue to you.
Image will remain same but text will change.
You will have to discuss about the text with content team members.

**Comment by ManasMadan** [comment]
Ok

**Comment by ManasMadan** [comment]
@aryav-022 Merging PR #6 closes this issue as completed
